// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto/message_sync.proto

package sync

import (
	proto1 "chain/types/proto"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SyncMessage_SyncMessageType int32

const (
	SyncMessage_Unknown              SyncMessage_SyncMessageType = 0
	SyncMessage_HeartBeatRequest     SyncMessage_SyncMessageType = 1
	SyncMessage_BlockRequest         SyncMessage_SyncMessageType = 2
	SyncMessage_BlockResponse        SyncMessage_SyncMessageType = 3
	SyncMessage_StateRequest         SyncMessage_SyncMessageType = 4
	SyncMessage_StateResponse        SyncMessage_SyncMessageType = 5
	SyncMessage_EpochRequest         SyncMessage_SyncMessageType = 6
	SyncMessage_EpochResponse        SyncMessage_SyncMessageType = 7
	SyncMessage_NodeStateRequest     SyncMessage_SyncMessageType = 8
	SyncMessage_NodeStateResponse    SyncMessage_SyncMessageType = 9
	SyncMessage_AccountStateRequest  SyncMessage_SyncMessageType = 10
	SyncMessage_AccountStateResponse SyncMessage_SyncMessageType = 11
	SyncMessage_ChainStateRequest    SyncMessage_SyncMessageType = 12
	SyncMessage_ChainStateResponse   SyncMessage_SyncMessageType = 13
)

var SyncMessage_SyncMessageType_name = map[int32]string{
	0:  "Unknown",
	1:  "HeartBeatRequest",
	2:  "BlockRequest",
	3:  "BlockResponse",
	4:  "StateRequest",
	5:  "StateResponse",
	6:  "EpochRequest",
	7:  "EpochResponse",
	8:  "NodeStateRequest",
	9:  "NodeStateResponse",
	10: "AccountStateRequest",
	11: "AccountStateResponse",
	12: "ChainStateRequest",
	13: "ChainStateResponse",
}

var SyncMessage_SyncMessageType_value = map[string]int32{
	"Unknown":              0,
	"HeartBeatRequest":     1,
	"BlockRequest":         2,
	"BlockResponse":        3,
	"StateRequest":         4,
	"StateResponse":        5,
	"EpochRequest":         6,
	"EpochResponse":        7,
	"NodeStateRequest":     8,
	"NodeStateResponse":    9,
	"AccountStateRequest":  10,
	"AccountStateResponse": 11,
	"ChainStateRequest":    12,
	"ChainStateResponse":   13,
}

func (x SyncMessage_SyncMessageType) String() string {
	return proto.EnumName(SyncMessage_SyncMessageType_name, int32(x))
}

func (SyncMessage_SyncMessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_eb29ea826754e922, []int{0, 0}
}

type BlockResponse_RespCode int32

const (
	BlockResponse_OK      BlockResponse_RespCode = 0
	BlockResponse_NOBLOCK BlockResponse_RespCode = 1
)

var BlockResponse_RespCode_name = map[int32]string{
	0: "OK",
	1: "NOBLOCK",
}

var BlockResponse_RespCode_value = map[string]int32{
	"OK":      0,
	"NOBLOCK": 1,
}

func (x BlockResponse_RespCode) String() string {
	return proto.EnumName(BlockResponse_RespCode_name, int32(x))
}

func (BlockResponse_RespCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_eb29ea826754e922, []int{3, 0}
}

type SyncMessage struct {
	MsgType              SyncMessage_SyncMessageType `protobuf:"varint,1,opt,name=MsgType,proto3,enum=proto.SyncMessage_SyncMessageType" json:"msgType"`
	Data                 []byte                      `protobuf:"bytes,2,opt,name=Data,proto3" json:"data"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *SyncMessage) Reset()         { *m = SyncMessage{} }
func (m *SyncMessage) String() string { return proto.CompactTextString(m) }
func (*SyncMessage) ProtoMessage()    {}
func (*SyncMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb29ea826754e922, []int{0}
}
func (m *SyncMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SyncMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *SyncMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncMessage.Merge(m, src)
}
func (m *SyncMessage) XXX_Size() int {
	return m.Size()
}
func (m *SyncMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncMessage.DiscardUnknown(m)
}

var xxx_messageInfo_SyncMessage proto.InternalMessageInfo

func (m *SyncMessage) GetMsgType() SyncMessage_SyncMessageType {
	if m != nil {
		return m.MsgType
	}
	return SyncMessage_Unknown
}

func (m *SyncMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type HeartBeatRequest struct {
	BlockHeight          uint64   `protobuf:"varint,1,opt,name=BlockHeight,proto3" json:"blockHeight"`
	StateRoot            []byte   `protobuf:"bytes,2,opt,name=StateRoot,proto3" json:"stateRoot"`
	SateVersion          uint64   `protobuf:"varint,3,opt,name=SateVersion,proto3" json:"stateRoot"`
	EpochRoot            []byte   `protobuf:"bytes,4,opt,name=EpochRoot,proto3" json:"epochRoot"`
	NodeRoot             []byte   `protobuf:"bytes,5,opt,name=NodeRoot,proto3" json:"nodeRoot"`
	ChainRoot            []byte   `protobuf:"bytes,6,opt,name=ChainRoot,proto3" json:"chainRoot"`
	AccountRoot          []byte   `protobuf:"bytes,7,opt,name=AccountRoot,proto3" json:"accountRoot"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartBeatRequest) Reset()         { *m = HeartBeatRequest{} }
func (m *HeartBeatRequest) String() string { return proto.CompactTextString(m) }
func (*HeartBeatRequest) ProtoMessage()    {}
func (*HeartBeatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb29ea826754e922, []int{1}
}
func (m *HeartBeatRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HeartBeatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *HeartBeatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartBeatRequest.Merge(m, src)
}
func (m *HeartBeatRequest) XXX_Size() int {
	return m.Size()
}
func (m *HeartBeatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartBeatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HeartBeatRequest proto.InternalMessageInfo

func (m *HeartBeatRequest) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *HeartBeatRequest) GetStateRoot() []byte {
	if m != nil {
		return m.StateRoot
	}
	return nil
}

func (m *HeartBeatRequest) GetSateVersion() uint64 {
	if m != nil {
		return m.SateVersion
	}
	return 0
}

func (m *HeartBeatRequest) GetEpochRoot() []byte {
	if m != nil {
		return m.EpochRoot
	}
	return nil
}

func (m *HeartBeatRequest) GetNodeRoot() []byte {
	if m != nil {
		return m.NodeRoot
	}
	return nil
}

func (m *HeartBeatRequest) GetChainRoot() []byte {
	if m != nil {
		return m.ChainRoot
	}
	return nil
}

func (m *HeartBeatRequest) GetAccountRoot() []byte {
	if m != nil {
		return m.AccountRoot
	}
	return nil
}

type BlockRequest struct {
	Height               uint64   `protobuf:"varint,1,opt,name=Height,proto3" json:"height"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockRequest) Reset()         { *m = BlockRequest{} }
func (m *BlockRequest) String() string { return proto.CompactTextString(m) }
func (*BlockRequest) ProtoMessage()    {}
func (*BlockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb29ea826754e922, []int{2}
}
func (m *BlockRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BlockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *BlockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockRequest.Merge(m, src)
}
func (m *BlockRequest) XXX_Size() int {
	return m.Size()
}
func (m *BlockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BlockRequest proto.InternalMessageInfo

func (m *BlockRequest) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

type BlockResponse struct {
	Height               uint64                 `protobuf:"varint,1,opt,name=Height,proto3" json:"height"`
	Code                 BlockResponse_RespCode `protobuf:"varint,2,opt,name=Code,proto3,enum=proto.BlockResponse_RespCode" json:"code"`
	Block                *proto1.Block          `protobuf:"bytes,3,opt,name=block,proto3" json:"block"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *BlockResponse) Reset()         { *m = BlockResponse{} }
func (m *BlockResponse) String() string { return proto.CompactTextString(m) }
func (*BlockResponse) ProtoMessage()    {}
func (*BlockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb29ea826754e922, []int{3}
}
func (m *BlockResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BlockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *BlockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockResponse.Merge(m, src)
}
func (m *BlockResponse) XXX_Size() int {
	return m.Size()
}
func (m *BlockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BlockResponse proto.InternalMessageInfo

func (m *BlockResponse) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *BlockResponse) GetCode() BlockResponse_RespCode {
	if m != nil {
		return m.Code
	}
	return BlockResponse_OK
}

func (m *BlockResponse) GetBlock() *proto1.Block {
	if m != nil {
		return m.Block
	}
	return nil
}

type StateRequest struct {
	StateVersion         uint64   `protobuf:"varint,1,opt,name=StateVersion,proto3" json:"stateVersion"`
	EpochRoot            []byte   `protobuf:"bytes,2,opt,name=EpochRoot,proto3" json:"epochRoot"`
	NodeRoot             []byte   `protobuf:"bytes,3,opt,name=NodeRoot,proto3" json:"nodeRoot"`
	ChainRoot            []byte   `protobuf:"bytes,4,opt,name=ChainRoot,proto3" json:"chainRoot"`
	AccountRoot          []byte   `protobuf:"bytes,5,opt,name=AccountRoot,proto3" json:"accountRoot"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StateRequest) Reset()         { *m = StateRequest{} }
func (m *StateRequest) String() string { return proto.CompactTextString(m) }
func (*StateRequest) ProtoMessage()    {}
func (*StateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb29ea826754e922, []int{4}
}
func (m *StateRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *StateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateRequest.Merge(m, src)
}
func (m *StateRequest) XXX_Size() int {
	return m.Size()
}
func (m *StateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StateRequest proto.InternalMessageInfo

func (m *StateRequest) GetStateVersion() uint64 {
	if m != nil {
		return m.StateVersion
	}
	return 0
}

func (m *StateRequest) GetEpochRoot() []byte {
	if m != nil {
		return m.EpochRoot
	}
	return nil
}

func (m *StateRequest) GetNodeRoot() []byte {
	if m != nil {
		return m.NodeRoot
	}
	return nil
}

func (m *StateRequest) GetChainRoot() []byte {
	if m != nil {
		return m.ChainRoot
	}
	return nil
}

func (m *StateRequest) GetAccountRoot() []byte {
	if m != nil {
		return m.AccountRoot
	}
	return nil
}

type StateResponse struct {
	StateRoot            []byte   `protobuf:"bytes,1,opt,name=StateRoot,proto3" json:"stateRoot"`
	StateVersion         uint64   `protobuf:"varint,2,opt,name=StateVersion,proto3" json:"stateVersion"`
	StateByVersion       []byte   `protobuf:"bytes,3,opt,name=StateByVersion,proto3" json:"StateByVersion"`
	EpochInfo            []byte   `protobuf:"bytes,4,opt,name=EpochInfo,proto3" json:"EpochInfo"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StateResponse) Reset()         { *m = StateResponse{} }
func (m *StateResponse) String() string { return proto.CompactTextString(m) }
func (*StateResponse) ProtoMessage()    {}
func (*StateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb29ea826754e922, []int{5}
}
func (m *StateResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *StateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateResponse.Merge(m, src)
}
func (m *StateResponse) XXX_Size() int {
	return m.Size()
}
func (m *StateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StateResponse proto.InternalMessageInfo

func (m *StateResponse) GetStateRoot() []byte {
	if m != nil {
		return m.StateRoot
	}
	return nil
}

func (m *StateResponse) GetStateVersion() uint64 {
	if m != nil {
		return m.StateVersion
	}
	return 0
}

func (m *StateResponse) GetStateByVersion() []byte {
	if m != nil {
		return m.StateByVersion
	}
	return nil
}

func (m *StateResponse) GetEpochInfo() []byte {
	if m != nil {
		return m.EpochInfo
	}
	return nil
}

type EpochResponse struct {
	Epoch                uint64   `protobuf:"varint,1,opt,name=Epoch,proto3" json:"epoch"`
	StartTimeStamp       uint64   `protobuf:"varint,2,opt,name=StartTimeStamp,proto3" json:"startTimeStamp"`
	StartHeight          uint64   `protobuf:"varint,3,opt,name=StartHeight,proto3" json:"startHeight"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EpochResponse) Reset()         { *m = EpochResponse{} }
func (m *EpochResponse) String() string { return proto.CompactTextString(m) }
func (*EpochResponse) ProtoMessage()    {}
func (*EpochResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb29ea826754e922, []int{6}
}
func (m *EpochResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EpochResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *EpochResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EpochResponse.Merge(m, src)
}
func (m *EpochResponse) XXX_Size() int {
	return m.Size()
}
func (m *EpochResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EpochResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EpochResponse proto.InternalMessageInfo

func (m *EpochResponse) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *EpochResponse) GetStartTimeStamp() uint64 {
	if m != nil {
		return m.StartTimeStamp
	}
	return 0
}

func (m *EpochResponse) GetStartHeight() uint64 {
	if m != nil {
		return m.StartHeight
	}
	return 0
}

type NodeResponse struct {
	StateVersion         uint64   `protobuf:"varint,1,opt,name=StateVersion,proto3" json:"stateVersion"`
	NodeRoot             []byte   `protobuf:"bytes,2,opt,name=NodeRoot,proto3" json:"nodeRoot"`
	StateData            []byte   `protobuf:"bytes,3,opt,name=StateData,proto3" json:"stateData"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeResponse) Reset()         { *m = NodeResponse{} }
func (m *NodeResponse) String() string { return proto.CompactTextString(m) }
func (*NodeResponse) ProtoMessage()    {}
func (*NodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eb29ea826754e922, []int{7}
}
func (m *NodeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *NodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeResponse.Merge(m, src)
}
func (m *NodeResponse) XXX_Size() int {
	return m.Size()
}
func (m *NodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NodeResponse proto.InternalMessageInfo

func (m *NodeResponse) GetStateVersion() uint64 {
	if m != nil {
		return m.StateVersion
	}
	return 0
}

func (m *NodeResponse) GetNodeRoot() []byte {
	if m != nil {
		return m.NodeRoot
	}
	return nil
}

func (m *NodeResponse) GetStateData() []byte {
	if m != nil {
		return m.StateData
	}
	return nil
}

func init() {
	proto.RegisterEnum("proto.SyncMessage_SyncMessageType", SyncMessage_SyncMessageType_name, SyncMessage_SyncMessageType_value)
	proto.RegisterEnum("proto.BlockResponse_RespCode", BlockResponse_RespCode_name, BlockResponse_RespCode_value)
	proto.RegisterType((*SyncMessage)(nil), "proto.SyncMessage")
	proto.RegisterType((*HeartBeatRequest)(nil), "proto.HeartBeatRequest")
	proto.RegisterType((*BlockRequest)(nil), "proto.BlockRequest")
	proto.RegisterType((*BlockResponse)(nil), "proto.BlockResponse")
	proto.RegisterType((*StateRequest)(nil), "proto.StateRequest")
	proto.RegisterType((*StateResponse)(nil), "proto.StateResponse")
	proto.RegisterType((*EpochResponse)(nil), "proto.EpochResponse")
	proto.RegisterType((*NodeResponse)(nil), "proto.NodeResponse")
}

func init() { proto.RegisterFile("proto/message_sync.proto", fileDescriptor_eb29ea826754e922) }

var fileDescriptor_eb29ea826754e922 = []byte{
	// 739 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xcd, 0x6e, 0xd3, 0x4a,
	0x18, 0xed, 0x38, 0xce, 0xdf, 0x67, 0xb7, 0x75, 0xe7, 0xf6, 0xde, 0x1b, 0x55, 0xb7, 0x71, 0xe5,
	0x55, 0xa5, 0x2b, 0x1a, 0x11, 0x58, 0xc1, 0x0a, 0x17, 0xa4, 0x56, 0xa5, 0xad, 0x34, 0x2d, 0x2c,
	0xd8, 0x20, 0xd7, 0x1d, 0x92, 0xa8, 0xc4, 0x13, 0xe2, 0xa9, 0x50, 0xde, 0x04, 0x89, 0x05, 0x0f,
	0xc0, 0x8e, 0x27, 0x60, 0xc9, 0x92, 0x25, 0x02, 0xc9, 0x42, 0x61, 0xe7, 0x57, 0x60, 0x83, 0xe6,
	0xc7, 0xf5, 0x0f, 0x8b, 0xa6, 0xac, 0xec, 0x39, 0xdf, 0xf9, 0x8e, 0xc6, 0xe7, 0xcc, 0x37, 0x86,
	0xce, 0x64, 0xca, 0x38, 0xeb, 0x8d, 0x69, 0x1c, 0x07, 0x03, 0xfa, 0x3c, 0x9e, 0x45, 0xe1, 0x8e,
	0x84, 0x70, 0x5d, 0x3e, 0x36, 0x60, 0xc0, 0x06, 0x4c, 0x41, 0x1b, 0x9b, 0xe1, 0x30, 0x18, 0x45,
	0x3d, 0x3e, 0x9b, 0xd0, 0xb8, 0xa7, 0x1a, 0xcf, 0x5e, 0xb2, 0xf0, 0x42, 0x95, 0xbd, 0xf7, 0x35,
	0xb0, 0x4e, 0x66, 0x51, 0x78, 0xa8, 0xc4, 0xf0, 0x3e, 0x34, 0x0f, 0xe3, 0xc1, 0xe9, 0x6c, 0x42,
	0x3b, 0x68, 0x0b, 0x6d, 0xaf, 0xf4, 0x3d, 0x45, 0xdc, 0x29, 0x90, 0x8a, 0xef, 0x82, 0xe9, 0x5b,
	0x69, 0xe2, 0x36, 0xc7, 0xaa, 0x8d, 0x64, 0xfd, 0xf8, 0x3f, 0x30, 0x1f, 0x06, 0x3c, 0xe8, 0x18,
	0x5b, 0x68, 0xdb, 0xf6, 0x5b, 0x69, 0xe2, 0x9a, 0xe7, 0x01, 0x0f, 0x88, 0x44, 0xbd, 0x0f, 0x06,
	0xac, 0x56, 0x74, 0xb0, 0x05, 0xcd, 0x27, 0xd1, 0x45, 0xc4, 0x5e, 0x47, 0xce, 0x12, 0x5e, 0x07,
	0x67, 0x8f, 0x06, 0x53, 0xee, 0xd3, 0x80, 0x13, 0xfa, 0xea, 0x92, 0xc6, 0xdc, 0x41, 0xd8, 0x01,
	0xdb, 0x17, 0xdb, 0xcf, 0x10, 0x03, 0xaf, 0xc1, 0xb2, 0x46, 0xe2, 0x09, 0x8b, 0x62, 0xea, 0xd4,
	0x04, 0xe9, 0x84, 0x07, 0x9c, 0x66, 0x24, 0x53, 0x90, 0x34, 0xa2, 0x49, 0x75, 0x41, 0x7a, 0x34,
	0x61, 0xe1, 0x30, 0x23, 0x35, 0x04, 0x49, 0x23, 0x9a, 0xd4, 0x14, 0x9b, 0x38, 0x62, 0xe7, 0xb4,
	0xa4, 0xd6, 0xc2, 0x7f, 0xc3, 0x5a, 0x01, 0xd5, 0xe4, 0x36, 0xfe, 0x17, 0xfe, 0x7a, 0x10, 0x86,
	0xec, 0x32, 0xe2, 0x25, 0x3e, 0xe0, 0x0e, 0xac, 0x97, 0x0b, 0xba, 0xc5, 0x12, 0x4a, 0xbb, 0x22,
	0x9f, 0x52, 0x83, 0x8d, 0xff, 0x01, 0x5c, 0x84, 0x35, 0x7d, 0xd9, 0xfb, 0x6a, 0xfc, 0x6e, 0x0a,
	0xbe, 0x0d, 0x96, 0x34, 0x60, 0x8f, 0x8e, 0x06, 0x43, 0x2e, 0x63, 0x33, 0xfd, 0xd5, 0x34, 0x71,
	0xad, 0xb3, 0x1c, 0x26, 0x45, 0x0e, 0xfe, 0x1f, 0xda, 0x4a, 0x9a, 0x31, 0xae, 0xf3, 0x59, 0x4e,
	0x13, 0xb7, 0x1d, 0x67, 0x20, 0xc9, 0xeb, 0xb8, 0x07, 0xd6, 0x49, 0xc0, 0xe9, 0x53, 0x3a, 0x8d,
	0x47, 0x2c, 0xea, 0xd4, 0xa4, 0x7e, 0x85, 0x5e, 0x64, 0x08, 0x75, 0xe5, 0xa3, 0x50, 0x37, 0x73,
	0x75, 0x9a, 0x81, 0x24, 0xaf, 0xe3, 0x6d, 0x68, 0x09, 0x2f, 0x25, 0xb7, 0x2e, 0xb9, 0x76, 0x9a,
	0xb8, 0xad, 0x48, 0x63, 0xe4, 0xaa, 0x2a, 0x64, 0xa5, 0x29, 0x92, 0xda, 0xc8, 0x65, 0xc3, 0x0c,
	0x24, 0x79, 0x5d, 0x98, 0xa2, 0x2d, 0x97, 0xf4, 0xa6, 0xa4, 0x4b, 0x53, 0x82, 0x1c, 0x26, 0x45,
	0x8e, 0xd7, 0x2f, 0x1f, 0x2d, 0xec, 0x41, 0xa3, 0x64, 0x29, 0xa4, 0x89, 0xdb, 0x18, 0x2a, 0x37,
	0x75, 0xc5, 0xfb, 0x88, 0x2a, 0xa7, 0x6f, 0x91, 0x2e, 0x7c, 0x1f, 0xcc, 0x5d, 0x76, 0x4e, 0xa5,
	0xf3, 0x2b, 0xfd, 0x4d, 0x3d, 0x61, 0x25, 0x9d, 0x1d, 0xf1, 0x22, 0x48, 0x6a, 0x70, 0x42, 0x61,
	0x82, 0x6c, 0xc2, 0xb7, 0xa0, 0x2e, 0x73, 0x95, 0x41, 0x58, 0x7d, 0xbb, 0xd8, 0xed, 0xb7, 0xd3,
	0xc4, 0x55, 0x65, 0xa2, 0x1e, 0x9e, 0x0b, 0xad, 0x4c, 0x0a, 0x37, 0xc0, 0x38, 0x3e, 0x70, 0x96,
	0xc4, 0x9c, 0x1d, 0x1d, 0xfb, 0x8f, 0x8f, 0x77, 0x0f, 0x1c, 0xe4, 0xfd, 0x44, 0xe5, 0x69, 0xc1,
	0x77, 0xf5, 0x3a, 0x0b, 0x5c, 0x7d, 0x87, 0x93, 0x26, 0xae, 0x1d, 0x17, 0x70, 0x52, 0x62, 0x95,
	0x43, 0x37, 0x6e, 0x10, 0x7a, 0x6d, 0xf1, 0xd0, 0xcd, 0x9b, 0x85, 0x5e, 0x5f, 0x20, 0xf4, 0x6f,
	0xa8, 0x72, 0x33, 0x94, 0x67, 0x03, 0x5d, 0x33, 0x1b, 0x55, 0xaf, 0x8c, 0x85, 0xbc, 0xba, 0x07,
	0x2b, 0x72, 0xed, 0xcf, 0x8a, 0x43, 0x65, 0xfb, 0x38, 0x4d, 0xdc, 0x4a, 0x85, 0x54, 0xd6, 0x57,
	0x3e, 0xef, 0x47, 0x2f, 0x58, 0xd1, 0x90, 0x2b, 0x90, 0xe4, 0xaf, 0xde, 0x3b, 0x54, 0xb9, 0xd2,
	0xb0, 0x0b, 0x75, 0x09, 0xe8, 0x54, 0xe5, 0x79, 0x51, 0x11, 0x29, 0x5c, 0xef, 0x6d, 0xca, 0x4f,
	0x47, 0x63, 0x71, 0xc1, 0x8d, 0x27, 0xfa, 0x9b, 0xe4, 0xde, 0xe2, 0x52, 0x85, 0x54, 0x98, 0xc2,
	0x7f, 0x89, 0xe8, 0x01, 0xa8, 0xe5, 0x37, 0x51, 0x9c, 0xc3, 0xa4, 0xc8, 0xf1, 0xde, 0x22, 0xb0,
	0x65, 0xd8, 0xd9, 0x06, 0xff, 0xec, 0xf4, 0x15, 0x0f, 0x94, 0x71, 0xdd, 0x81, 0x92, 0x9d, 0xf2,
	0xd7, 0x54, 0xab, 0xc4, 0x2b, 0x40, 0x92, 0xd7, 0xfd, 0x8d, 0x4f, 0xf3, 0x2e, 0xfa, 0x3c, 0xef,
	0xa2, 0x2f, 0xf3, 0x2e, 0xfa, 0x3e, 0xef, 0xa2, 0x37, 0x3f, 0xba, 0x4b, 0xcf, 0x4c, 0xf1, 0xc7,
	0x3d, 0x6b, 0xc8, 0xb9, 0xbb, 0xf3, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x28, 0xe8, 0xba, 0xd5, 0x8e,
	0x07, 0x00, 0x00,
}

func (m *SyncMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SyncMessage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SyncMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Data) > 0 {
		i -= len(m.Data)
		copy(dAtA[i:], m.Data)
		i = encodeVarintMessageSync(dAtA, i, uint64(len(m.Data)))
		i--
		dAtA[i] = 0x12
	}
	if m.MsgType != 0 {
		i = encodeVarintMessageSync(dAtA, i, uint64(m.MsgType))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *HeartBeatRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HeartBeatRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HeartBeatRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.AccountRoot) > 0 {
		i -= len(m.AccountRoot)
		copy(dAtA[i:], m.AccountRoot)
		i = encodeVarintMessageSync(dAtA, i, uint64(len(m.AccountRoot)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.ChainRoot) > 0 {
		i -= len(m.ChainRoot)
		copy(dAtA[i:], m.ChainRoot)
		i = encodeVarintMessageSync(dAtA, i, uint64(len(m.ChainRoot)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.NodeRoot) > 0 {
		i -= len(m.NodeRoot)
		copy(dAtA[i:], m.NodeRoot)
		i = encodeVarintMessageSync(dAtA, i, uint64(len(m.NodeRoot)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.EpochRoot) > 0 {
		i -= len(m.EpochRoot)
		copy(dAtA[i:], m.EpochRoot)
		i = encodeVarintMessageSync(dAtA, i, uint64(len(m.EpochRoot)))
		i--
		dAtA[i] = 0x22
	}
	if m.SateVersion != 0 {
		i = encodeVarintMessageSync(dAtA, i, uint64(m.SateVersion))
		i--
		dAtA[i] = 0x18
	}
	if len(m.StateRoot) > 0 {
		i -= len(m.StateRoot)
		copy(dAtA[i:], m.StateRoot)
		i = encodeVarintMessageSync(dAtA, i, uint64(len(m.StateRoot)))
		i--
		dAtA[i] = 0x12
	}
	if m.BlockHeight != 0 {
		i = encodeVarintMessageSync(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *BlockRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BlockRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BlockRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Height != 0 {
		i = encodeVarintMessageSync(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *BlockResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BlockResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BlockResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Block != nil {
		{
			size, err := m.Block.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintMessageSync(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.Code != 0 {
		i = encodeVarintMessageSync(dAtA, i, uint64(m.Code))
		i--
		dAtA[i] = 0x10
	}
	if m.Height != 0 {
		i = encodeVarintMessageSync(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *StateRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StateRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StateRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.AccountRoot) > 0 {
		i -= len(m.AccountRoot)
		copy(dAtA[i:], m.AccountRoot)
		i = encodeVarintMessageSync(dAtA, i, uint64(len(m.AccountRoot)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ChainRoot) > 0 {
		i -= len(m.ChainRoot)
		copy(dAtA[i:], m.ChainRoot)
		i = encodeVarintMessageSync(dAtA, i, uint64(len(m.ChainRoot)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.NodeRoot) > 0 {
		i -= len(m.NodeRoot)
		copy(dAtA[i:], m.NodeRoot)
		i = encodeVarintMessageSync(dAtA, i, uint64(len(m.NodeRoot)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.EpochRoot) > 0 {
		i -= len(m.EpochRoot)
		copy(dAtA[i:], m.EpochRoot)
		i = encodeVarintMessageSync(dAtA, i, uint64(len(m.EpochRoot)))
		i--
		dAtA[i] = 0x12
	}
	if m.StateVersion != 0 {
		i = encodeVarintMessageSync(dAtA, i, uint64(m.StateVersion))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *StateResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StateResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StateResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.EpochInfo) > 0 {
		i -= len(m.EpochInfo)
		copy(dAtA[i:], m.EpochInfo)
		i = encodeVarintMessageSync(dAtA, i, uint64(len(m.EpochInfo)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.StateByVersion) > 0 {
		i -= len(m.StateByVersion)
		copy(dAtA[i:], m.StateByVersion)
		i = encodeVarintMessageSync(dAtA, i, uint64(len(m.StateByVersion)))
		i--
		dAtA[i] = 0x1a
	}
	if m.StateVersion != 0 {
		i = encodeVarintMessageSync(dAtA, i, uint64(m.StateVersion))
		i--
		dAtA[i] = 0x10
	}
	if len(m.StateRoot) > 0 {
		i -= len(m.StateRoot)
		copy(dAtA[i:], m.StateRoot)
		i = encodeVarintMessageSync(dAtA, i, uint64(len(m.StateRoot)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EpochResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EpochResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EpochResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.StartHeight != 0 {
		i = encodeVarintMessageSync(dAtA, i, uint64(m.StartHeight))
		i--
		dAtA[i] = 0x18
	}
	if m.StartTimeStamp != 0 {
		i = encodeVarintMessageSync(dAtA, i, uint64(m.StartTimeStamp))
		i--
		dAtA[i] = 0x10
	}
	if m.Epoch != 0 {
		i = encodeVarintMessageSync(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *NodeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NodeResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NodeResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.StateData) > 0 {
		i -= len(m.StateData)
		copy(dAtA[i:], m.StateData)
		i = encodeVarintMessageSync(dAtA, i, uint64(len(m.StateData)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.NodeRoot) > 0 {
		i -= len(m.NodeRoot)
		copy(dAtA[i:], m.NodeRoot)
		i = encodeVarintMessageSync(dAtA, i, uint64(len(m.NodeRoot)))
		i--
		dAtA[i] = 0x12
	}
	if m.StateVersion != 0 {
		i = encodeVarintMessageSync(dAtA, i, uint64(m.StateVersion))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintMessageSync(dAtA []byte, offset int, v uint64) int {
	offset -= sovMessageSync(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SyncMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MsgType != 0 {
		n += 1 + sovMessageSync(uint64(m.MsgType))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovMessageSync(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *HeartBeatRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BlockHeight != 0 {
		n += 1 + sovMessageSync(uint64(m.BlockHeight))
	}
	l = len(m.StateRoot)
	if l > 0 {
		n += 1 + l + sovMessageSync(uint64(l))
	}
	if m.SateVersion != 0 {
		n += 1 + sovMessageSync(uint64(m.SateVersion))
	}
	l = len(m.EpochRoot)
	if l > 0 {
		n += 1 + l + sovMessageSync(uint64(l))
	}
	l = len(m.NodeRoot)
	if l > 0 {
		n += 1 + l + sovMessageSync(uint64(l))
	}
	l = len(m.ChainRoot)
	if l > 0 {
		n += 1 + l + sovMessageSync(uint64(l))
	}
	l = len(m.AccountRoot)
	if l > 0 {
		n += 1 + l + sovMessageSync(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *BlockRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Height != 0 {
		n += 1 + sovMessageSync(uint64(m.Height))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *BlockResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Height != 0 {
		n += 1 + sovMessageSync(uint64(m.Height))
	}
	if m.Code != 0 {
		n += 1 + sovMessageSync(uint64(m.Code))
	}
	if m.Block != nil {
		l = m.Block.Size()
		n += 1 + l + sovMessageSync(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *StateRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.StateVersion != 0 {
		n += 1 + sovMessageSync(uint64(m.StateVersion))
	}
	l = len(m.EpochRoot)
	if l > 0 {
		n += 1 + l + sovMessageSync(uint64(l))
	}
	l = len(m.NodeRoot)
	if l > 0 {
		n += 1 + l + sovMessageSync(uint64(l))
	}
	l = len(m.ChainRoot)
	if l > 0 {
		n += 1 + l + sovMessageSync(uint64(l))
	}
	l = len(m.AccountRoot)
	if l > 0 {
		n += 1 + l + sovMessageSync(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *StateResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.StateRoot)
	if l > 0 {
		n += 1 + l + sovMessageSync(uint64(l))
	}
	if m.StateVersion != 0 {
		n += 1 + sovMessageSync(uint64(m.StateVersion))
	}
	l = len(m.StateByVersion)
	if l > 0 {
		n += 1 + l + sovMessageSync(uint64(l))
	}
	l = len(m.EpochInfo)
	if l > 0 {
		n += 1 + l + sovMessageSync(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *EpochResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Epoch != 0 {
		n += 1 + sovMessageSync(uint64(m.Epoch))
	}
	if m.StartTimeStamp != 0 {
		n += 1 + sovMessageSync(uint64(m.StartTimeStamp))
	}
	if m.StartHeight != 0 {
		n += 1 + sovMessageSync(uint64(m.StartHeight))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *NodeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.StateVersion != 0 {
		n += 1 + sovMessageSync(uint64(m.StateVersion))
	}
	l = len(m.NodeRoot)
	if l > 0 {
		n += 1 + l + sovMessageSync(uint64(l))
	}
	l = len(m.StateData)
	if l > 0 {
		n += 1 + l + sovMessageSync(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovMessageSync(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozMessageSync(x uint64) (n int) {
	return sovMessageSync(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SyncMessage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessageSync
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SyncMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SyncMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MsgType", wireType)
			}
			m.MsgType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageSync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MsgType |= SyncMessage_SyncMessageType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageSync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMessageSync
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMessageSync
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMessageSync(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMessageSync
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *HeartBeatRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessageSync
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HeartBeatRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HeartBeatRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageSync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StateRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageSync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMessageSync
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMessageSync
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StateRoot = append(m.StateRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.StateRoot == nil {
				m.StateRoot = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SateVersion", wireType)
			}
			m.SateVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageSync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SateVersion |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageSync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMessageSync
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMessageSync
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EpochRoot = append(m.EpochRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.EpochRoot == nil {
				m.EpochRoot = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageSync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMessageSync
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMessageSync
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodeRoot = append(m.NodeRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.NodeRoot == nil {
				m.NodeRoot = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageSync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMessageSync
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMessageSync
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainRoot = append(m.ChainRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.ChainRoot == nil {
				m.ChainRoot = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageSync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMessageSync
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMessageSync
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccountRoot = append(m.AccountRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.AccountRoot == nil {
				m.AccountRoot = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMessageSync(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMessageSync
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BlockRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessageSync
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BlockRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BlockRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageSync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMessageSync(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMessageSync
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *BlockResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessageSync
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BlockResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BlockResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageSync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			m.Code = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageSync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Code |= BlockResponse_RespCode(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Block", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageSync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMessageSync
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthMessageSync
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Block == nil {
				m.Block = &proto1.Block{}
			}
			if err := m.Block.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMessageSync(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMessageSync
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StateRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessageSync
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StateRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StateRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StateVersion", wireType)
			}
			m.StateVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageSync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StateVersion |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageSync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMessageSync
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMessageSync
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EpochRoot = append(m.EpochRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.EpochRoot == nil {
				m.EpochRoot = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageSync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMessageSync
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMessageSync
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodeRoot = append(m.NodeRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.NodeRoot == nil {
				m.NodeRoot = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageSync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMessageSync
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMessageSync
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainRoot = append(m.ChainRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.ChainRoot == nil {
				m.ChainRoot = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageSync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMessageSync
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMessageSync
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccountRoot = append(m.AccountRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.AccountRoot == nil {
				m.AccountRoot = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMessageSync(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMessageSync
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StateResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessageSync
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StateResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StateResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StateRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageSync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMessageSync
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMessageSync
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StateRoot = append(m.StateRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.StateRoot == nil {
				m.StateRoot = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StateVersion", wireType)
			}
			m.StateVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageSync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StateVersion |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StateByVersion", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageSync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMessageSync
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMessageSync
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StateByVersion = append(m.StateByVersion[:0], dAtA[iNdEx:postIndex]...)
			if m.StateByVersion == nil {
				m.StateByVersion = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochInfo", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageSync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMessageSync
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMessageSync
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EpochInfo = append(m.EpochInfo[:0], dAtA[iNdEx:postIndex]...)
			if m.EpochInfo == nil {
				m.EpochInfo = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMessageSync(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMessageSync
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EpochResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessageSync
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EpochResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EpochResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageSync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTimeStamp", wireType)
			}
			m.StartTimeStamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageSync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartTimeStamp |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartHeight", wireType)
			}
			m.StartHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageSync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMessageSync(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMessageSync
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NodeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMessageSync
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NodeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NodeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StateVersion", wireType)
			}
			m.StateVersion = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageSync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StateVersion |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageSync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMessageSync
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMessageSync
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodeRoot = append(m.NodeRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.NodeRoot == nil {
				m.NodeRoot = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StateData", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMessageSync
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMessageSync
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthMessageSync
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StateData = append(m.StateData[:0], dAtA[iNdEx:postIndex]...)
			if m.StateData == nil {
				m.StateData = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMessageSync(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthMessageSync
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMessageSync(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMessageSync
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMessageSync
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMessageSync
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthMessageSync
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupMessageSync
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthMessageSync
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthMessageSync        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMessageSync          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupMessageSync = fmt.Errorf("proto: unexpected end of group")
)
